

name: CI/Get File

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '25 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Update_adblock-hosts:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Generate File
        run: |
          curl -s -L https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt https://easylist-downloads.adblockplus.org/malwaredomains_full.txt https://easylist-downloads.adblockplus.org/fanboy-social.txt > adblock.unsorted
          sort -u adblock.unsorted | grep ^\|\|.*\^$ | grep -v \/ > adblock.sorted
          sed 's/[\|^]//g' < adblock.sorted > adblock.hosts
          rm adblock.unsorted adblock.sorted
      - name: Upload file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: adblock.hosts
          asset_name: adblock.hosts
          tag: v1.0.0
          overwrite: true
          body: "Initial release"
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Upload file to GitHub
        uses: LasyIsLazy/github-upload-action@v0.1.0
        with:
          access-token: ${{ secrets.TOKEN }}
          file-path: adblock.hosts
          owner: Thomas311926
          repo: adlist
          branch-name: main
          commit-message: "update file"
  Update_list-txt:
      runs-on: ubuntu-latest
      if: ${{ always() }}
      needs: Update_adblock-hosts
      steps:
          - uses: actions/checkout@v3
          - name: Generate File
            run: wget "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext" -O list.txt
          - name: Upload file to release
            uses: svenstaro/upload-release-action@v2
            with:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
              file: list.txt
              asset_name: list.txt
              tag: v1.0.0
              overwrite: true
              body: "Initial release"
          - name: Setup node
            uses: actions/setup-node@v1
          - name: Upload file to GitHub
            uses: LasyIsLazy/github-upload-action@v0.1.0
            with:
              access-token: ${{ secrets.TOKEN }}
              file-path: list.txt
              owner: Thomas311926
              repo: adlist
              branch-name: main
              commit-message: "update file"
  Update_macvendor-db:
      runs-on: ubuntu-latest
      if: ${{ always() }}
      needs: [Update_adblock-hosts,Update_list-txt]
      steps:
          - uses: actions/checkout@v3
          - name: Generate File
            run: wget "https://ftl.pi-hole.net/macvendor.db"
          - name: Upload file to release
            uses: svenstaro/upload-release-action@v2
            with:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
              file: macvendor.db
              asset_name: macvendor.db
              tag: v1.0.0
              overwrite: true
              body: "Initial release"
          - name: Setup node
            uses: actions/setup-node@v1
          - name: Upload file to GitHub
            uses: LasyIsLazy/github-upload-action@v0.1.0
            with:
              access-token: ${{ secrets.TOKEN }}
              file-path: macvendor.db
              owner: Thomas311926
              repo: adlist
              branch-name: main
              commit-message: "update file"
